USER_LIB_PATH := $(realpath ./lib)
ARDUINO_LIBS  := RTCLib RTCLib/DS3231 Time Timezone Wire
BOARD_TAG     := uno
ARDUINO_PORT  := /dev/ttyUSB0
CXXFLAGS      += -std=gnu++11
CFLAGS        += -std=gnu++11


include /usr/share/arduino/Arduino.mk
